// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: InteractWordV2.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace BLiveAPI.Protos {

  /// <summary>Holder for reflection information generated from InteractWordV2.proto</summary>
  public static partial class InteractWordV2Reflection {

    #region Descriptor
    /// <summary>File descriptor for InteractWordV2.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static InteractWordV2Reflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChRJbnRlcmFjdFdvcmRWMi5wcm90bxIPQkxpdmVBUEkuUHJvdG9zGgpCQVNF",
            "LnByb3RvIr4ECg5JbnRlcmFjdFdvcmRWMhILCgN1aWQYASABKAQSDQoFdW5h",
            "bWUYAiABKAkSEwoLdW5hbWVfY29sb3IYAyABKAkSEgoKaWRlbnRpdGllcxgE",
            "IAMoBBIQCghtc2dfdHlwZRgFIAEoBBIOCgZyb29taWQYBiABKAQSEQoJdGlt",
            "ZXN0YW1wGAcgASgEEg0KBXNjb3JlGAggASgEEiIKCmZhbnNfbWVkYWwYCSAB",
            "KAsyDi5GYW5zTWVkYWxJbmZvEhEKCWlzX3NwcmVhZBgKIAEoBBITCgtzcHJl",
            "YWRfaW5mbxgLIAEoCRInCgxjb250cmlidXRpb24YDCABKAsyES5Db250cmli",
            "dXRpb25JbmZvEhMKC3NwcmVhZF9kZXNjGA0gASgJEhEKCXRhaWxfaWNvbhgO",
            "IAEoBBIUCgx0cmlnZ2VyX3RpbWUYDyABKAQSFgoOcHJpdmlsZWdlX3R5cGUY",
            "ECABKAQSFgoOY29yZV91c2VyX3R5cGUYESABKAQSEQoJdGFpbF90ZXh0GBIg",
            "ASgJEiwKD2NvbnRyaWJ1dGlvbl92MhgTIAEoCzITLkNvbnRyaWJ1dGlvbklu",
            "Zm9WMhIlCgtncm91cF9tZWRhbBgUIAEoCzIQLkdyb3VwTWVkYWxCcmllZhIS",
            "Cgppc19teXN0ZXJ5GBUgASgIEhgKBXVpbmZvGBYgASgLMgkuVXNlckluZm8S",
            "KgoNcmVsYXRpb25fdGFpbBgXIAEoCzITLlVzZXJBbmNob3JSZWxhdGlvbkIS",
            "qgIPQkxpdmVBUEkuUHJvdG9zYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::BASEReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::BLiveAPI.Protos.InteractWordV2), global::BLiveAPI.Protos.InteractWordV2.Parser, new[]{ "Uid", "Uname", "UnameColor", "Identities", "MsgType", "Roomid", "Timestamp", "Score", "FansMedal", "IsSpread", "SpreadInfo", "Contribution", "SpreadDesc", "TailIcon", "TriggerTime", "PrivilegeType", "CoreUserType", "TailText", "ContributionV2", "GroupMedal", "IsMystery", "Uinfo", "RelationTail" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class InteractWordV2 : pb::IMessage<InteractWordV2>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<InteractWordV2> _parser = new pb::MessageParser<InteractWordV2>(() => new InteractWordV2());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<InteractWordV2> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::BLiveAPI.Protos.InteractWordV2Reflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public InteractWordV2() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public InteractWordV2(InteractWordV2 other) : this() {
      uid_ = other.uid_;
      uname_ = other.uname_;
      unameColor_ = other.unameColor_;
      identities_ = other.identities_.Clone();
      msgType_ = other.msgType_;
      roomid_ = other.roomid_;
      timestamp_ = other.timestamp_;
      score_ = other.score_;
      fansMedal_ = other.fansMedal_ != null ? other.fansMedal_.Clone() : null;
      isSpread_ = other.isSpread_;
      spreadInfo_ = other.spreadInfo_;
      contribution_ = other.contribution_ != null ? other.contribution_.Clone() : null;
      spreadDesc_ = other.spreadDesc_;
      tailIcon_ = other.tailIcon_;
      triggerTime_ = other.triggerTime_;
      privilegeType_ = other.privilegeType_;
      coreUserType_ = other.coreUserType_;
      tailText_ = other.tailText_;
      contributionV2_ = other.contributionV2_ != null ? other.contributionV2_.Clone() : null;
      groupMedal_ = other.groupMedal_ != null ? other.groupMedal_.Clone() : null;
      isMystery_ = other.isMystery_;
      uinfo_ = other.uinfo_ != null ? other.uinfo_.Clone() : null;
      relationTail_ = other.relationTail_ != null ? other.relationTail_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public InteractWordV2 Clone() {
      return new InteractWordV2(this);
    }

    /// <summary>Field number for the "uid" field.</summary>
    public const int UidFieldNumber = 1;
    private ulong uid_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong Uid {
      get { return uid_; }
      set {
        uid_ = value;
      }
    }

    /// <summary>Field number for the "uname" field.</summary>
    public const int UnameFieldNumber = 2;
    private string uname_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Uname {
      get { return uname_; }
      set {
        uname_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "uname_color" field.</summary>
    public const int UnameColorFieldNumber = 3;
    private string unameColor_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string UnameColor {
      get { return unameColor_; }
      set {
        unameColor_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "identities" field.</summary>
    public const int IdentitiesFieldNumber = 4;
    private static readonly pb::FieldCodec<ulong> _repeated_identities_codec
        = pb::FieldCodec.ForUInt64(34);
    private readonly pbc::RepeatedField<ulong> identities_ = new pbc::RepeatedField<ulong>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<ulong> Identities {
      get { return identities_; }
    }

    /// <summary>Field number for the "msg_type" field.</summary>
    public const int MsgTypeFieldNumber = 5;
    private ulong msgType_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong MsgType {
      get { return msgType_; }
      set {
        msgType_ = value;
      }
    }

    /// <summary>Field number for the "roomid" field.</summary>
    public const int RoomidFieldNumber = 6;
    private ulong roomid_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong Roomid {
      get { return roomid_; }
      set {
        roomid_ = value;
      }
    }

    /// <summary>Field number for the "timestamp" field.</summary>
    public const int TimestampFieldNumber = 7;
    private ulong timestamp_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong Timestamp {
      get { return timestamp_; }
      set {
        timestamp_ = value;
      }
    }

    /// <summary>Field number for the "score" field.</summary>
    public const int ScoreFieldNumber = 8;
    private ulong score_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong Score {
      get { return score_; }
      set {
        score_ = value;
      }
    }

    /// <summary>Field number for the "fans_medal" field.</summary>
    public const int FansMedalFieldNumber = 9;
    private global::FansMedalInfo fansMedal_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::FansMedalInfo FansMedal {
      get { return fansMedal_; }
      set {
        fansMedal_ = value;
      }
    }

    /// <summary>Field number for the "is_spread" field.</summary>
    public const int IsSpreadFieldNumber = 10;
    private ulong isSpread_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong IsSpread {
      get { return isSpread_; }
      set {
        isSpread_ = value;
      }
    }

    /// <summary>Field number for the "spread_info" field.</summary>
    public const int SpreadInfoFieldNumber = 11;
    private string spreadInfo_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string SpreadInfo {
      get { return spreadInfo_; }
      set {
        spreadInfo_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "contribution" field.</summary>
    public const int ContributionFieldNumber = 12;
    private global::ContributionInfo contribution_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::ContributionInfo Contribution {
      get { return contribution_; }
      set {
        contribution_ = value;
      }
    }

    /// <summary>Field number for the "spread_desc" field.</summary>
    public const int SpreadDescFieldNumber = 13;
    private string spreadDesc_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string SpreadDesc {
      get { return spreadDesc_; }
      set {
        spreadDesc_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "tail_icon" field.</summary>
    public const int TailIconFieldNumber = 14;
    private ulong tailIcon_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong TailIcon {
      get { return tailIcon_; }
      set {
        tailIcon_ = value;
      }
    }

    /// <summary>Field number for the "trigger_time" field.</summary>
    public const int TriggerTimeFieldNumber = 15;
    private ulong triggerTime_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong TriggerTime {
      get { return triggerTime_; }
      set {
        triggerTime_ = value;
      }
    }

    /// <summary>Field number for the "privilege_type" field.</summary>
    public const int PrivilegeTypeFieldNumber = 16;
    private ulong privilegeType_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong PrivilegeType {
      get { return privilegeType_; }
      set {
        privilegeType_ = value;
      }
    }

    /// <summary>Field number for the "core_user_type" field.</summary>
    public const int CoreUserTypeFieldNumber = 17;
    private ulong coreUserType_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong CoreUserType {
      get { return coreUserType_; }
      set {
        coreUserType_ = value;
      }
    }

    /// <summary>Field number for the "tail_text" field.</summary>
    public const int TailTextFieldNumber = 18;
    private string tailText_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string TailText {
      get { return tailText_; }
      set {
        tailText_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "contribution_v2" field.</summary>
    public const int ContributionV2FieldNumber = 19;
    private global::ContributionInfoV2 contributionV2_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::ContributionInfoV2 ContributionV2 {
      get { return contributionV2_; }
      set {
        contributionV2_ = value;
      }
    }

    /// <summary>Field number for the "group_medal" field.</summary>
    public const int GroupMedalFieldNumber = 20;
    private global::GroupMedalBrief groupMedal_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::GroupMedalBrief GroupMedal {
      get { return groupMedal_; }
      set {
        groupMedal_ = value;
      }
    }

    /// <summary>Field number for the "is_mystery" field.</summary>
    public const int IsMysteryFieldNumber = 21;
    private bool isMystery_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool IsMystery {
      get { return isMystery_; }
      set {
        isMystery_ = value;
      }
    }

    /// <summary>Field number for the "uinfo" field.</summary>
    public const int UinfoFieldNumber = 22;
    private global::UserInfo uinfo_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::UserInfo Uinfo {
      get { return uinfo_; }
      set {
        uinfo_ = value;
      }
    }

    /// <summary>Field number for the "relation_tail" field.</summary>
    public const int RelationTailFieldNumber = 23;
    private global::UserAnchorRelation relationTail_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::UserAnchorRelation RelationTail {
      get { return relationTail_; }
      set {
        relationTail_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as InteractWordV2);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(InteractWordV2 other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Uid != other.Uid) return false;
      if (Uname != other.Uname) return false;
      if (UnameColor != other.UnameColor) return false;
      if(!identities_.Equals(other.identities_)) return false;
      if (MsgType != other.MsgType) return false;
      if (Roomid != other.Roomid) return false;
      if (Timestamp != other.Timestamp) return false;
      if (Score != other.Score) return false;
      if (!object.Equals(FansMedal, other.FansMedal)) return false;
      if (IsSpread != other.IsSpread) return false;
      if (SpreadInfo != other.SpreadInfo) return false;
      if (!object.Equals(Contribution, other.Contribution)) return false;
      if (SpreadDesc != other.SpreadDesc) return false;
      if (TailIcon != other.TailIcon) return false;
      if (TriggerTime != other.TriggerTime) return false;
      if (PrivilegeType != other.PrivilegeType) return false;
      if (CoreUserType != other.CoreUserType) return false;
      if (TailText != other.TailText) return false;
      if (!object.Equals(ContributionV2, other.ContributionV2)) return false;
      if (!object.Equals(GroupMedal, other.GroupMedal)) return false;
      if (IsMystery != other.IsMystery) return false;
      if (!object.Equals(Uinfo, other.Uinfo)) return false;
      if (!object.Equals(RelationTail, other.RelationTail)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Uid != 0UL) hash ^= Uid.GetHashCode();
      if (Uname.Length != 0) hash ^= Uname.GetHashCode();
      if (UnameColor.Length != 0) hash ^= UnameColor.GetHashCode();
      hash ^= identities_.GetHashCode();
      if (MsgType != 0UL) hash ^= MsgType.GetHashCode();
      if (Roomid != 0UL) hash ^= Roomid.GetHashCode();
      if (Timestamp != 0UL) hash ^= Timestamp.GetHashCode();
      if (Score != 0UL) hash ^= Score.GetHashCode();
      if (fansMedal_ != null) hash ^= FansMedal.GetHashCode();
      if (IsSpread != 0UL) hash ^= IsSpread.GetHashCode();
      if (SpreadInfo.Length != 0) hash ^= SpreadInfo.GetHashCode();
      if (contribution_ != null) hash ^= Contribution.GetHashCode();
      if (SpreadDesc.Length != 0) hash ^= SpreadDesc.GetHashCode();
      if (TailIcon != 0UL) hash ^= TailIcon.GetHashCode();
      if (TriggerTime != 0UL) hash ^= TriggerTime.GetHashCode();
      if (PrivilegeType != 0UL) hash ^= PrivilegeType.GetHashCode();
      if (CoreUserType != 0UL) hash ^= CoreUserType.GetHashCode();
      if (TailText.Length != 0) hash ^= TailText.GetHashCode();
      if (contributionV2_ != null) hash ^= ContributionV2.GetHashCode();
      if (groupMedal_ != null) hash ^= GroupMedal.GetHashCode();
      if (IsMystery != false) hash ^= IsMystery.GetHashCode();
      if (uinfo_ != null) hash ^= Uinfo.GetHashCode();
      if (relationTail_ != null) hash ^= RelationTail.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Uid != 0UL) {
        output.WriteRawTag(8);
        output.WriteUInt64(Uid);
      }
      if (Uname.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Uname);
      }
      if (UnameColor.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(UnameColor);
      }
      identities_.WriteTo(output, _repeated_identities_codec);
      if (MsgType != 0UL) {
        output.WriteRawTag(40);
        output.WriteUInt64(MsgType);
      }
      if (Roomid != 0UL) {
        output.WriteRawTag(48);
        output.WriteUInt64(Roomid);
      }
      if (Timestamp != 0UL) {
        output.WriteRawTag(56);
        output.WriteUInt64(Timestamp);
      }
      if (Score != 0UL) {
        output.WriteRawTag(64);
        output.WriteUInt64(Score);
      }
      if (fansMedal_ != null) {
        output.WriteRawTag(74);
        output.WriteMessage(FansMedal);
      }
      if (IsSpread != 0UL) {
        output.WriteRawTag(80);
        output.WriteUInt64(IsSpread);
      }
      if (SpreadInfo.Length != 0) {
        output.WriteRawTag(90);
        output.WriteString(SpreadInfo);
      }
      if (contribution_ != null) {
        output.WriteRawTag(98);
        output.WriteMessage(Contribution);
      }
      if (SpreadDesc.Length != 0) {
        output.WriteRawTag(106);
        output.WriteString(SpreadDesc);
      }
      if (TailIcon != 0UL) {
        output.WriteRawTag(112);
        output.WriteUInt64(TailIcon);
      }
      if (TriggerTime != 0UL) {
        output.WriteRawTag(120);
        output.WriteUInt64(TriggerTime);
      }
      if (PrivilegeType != 0UL) {
        output.WriteRawTag(128, 1);
        output.WriteUInt64(PrivilegeType);
      }
      if (CoreUserType != 0UL) {
        output.WriteRawTag(136, 1);
        output.WriteUInt64(CoreUserType);
      }
      if (TailText.Length != 0) {
        output.WriteRawTag(146, 1);
        output.WriteString(TailText);
      }
      if (contributionV2_ != null) {
        output.WriteRawTag(154, 1);
        output.WriteMessage(ContributionV2);
      }
      if (groupMedal_ != null) {
        output.WriteRawTag(162, 1);
        output.WriteMessage(GroupMedal);
      }
      if (IsMystery != false) {
        output.WriteRawTag(168, 1);
        output.WriteBool(IsMystery);
      }
      if (uinfo_ != null) {
        output.WriteRawTag(178, 1);
        output.WriteMessage(Uinfo);
      }
      if (relationTail_ != null) {
        output.WriteRawTag(186, 1);
        output.WriteMessage(RelationTail);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Uid != 0UL) {
        output.WriteRawTag(8);
        output.WriteUInt64(Uid);
      }
      if (Uname.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Uname);
      }
      if (UnameColor.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(UnameColor);
      }
      identities_.WriteTo(ref output, _repeated_identities_codec);
      if (MsgType != 0UL) {
        output.WriteRawTag(40);
        output.WriteUInt64(MsgType);
      }
      if (Roomid != 0UL) {
        output.WriteRawTag(48);
        output.WriteUInt64(Roomid);
      }
      if (Timestamp != 0UL) {
        output.WriteRawTag(56);
        output.WriteUInt64(Timestamp);
      }
      if (Score != 0UL) {
        output.WriteRawTag(64);
        output.WriteUInt64(Score);
      }
      if (fansMedal_ != null) {
        output.WriteRawTag(74);
        output.WriteMessage(FansMedal);
      }
      if (IsSpread != 0UL) {
        output.WriteRawTag(80);
        output.WriteUInt64(IsSpread);
      }
      if (SpreadInfo.Length != 0) {
        output.WriteRawTag(90);
        output.WriteString(SpreadInfo);
      }
      if (contribution_ != null) {
        output.WriteRawTag(98);
        output.WriteMessage(Contribution);
      }
      if (SpreadDesc.Length != 0) {
        output.WriteRawTag(106);
        output.WriteString(SpreadDesc);
      }
      if (TailIcon != 0UL) {
        output.WriteRawTag(112);
        output.WriteUInt64(TailIcon);
      }
      if (TriggerTime != 0UL) {
        output.WriteRawTag(120);
        output.WriteUInt64(TriggerTime);
      }
      if (PrivilegeType != 0UL) {
        output.WriteRawTag(128, 1);
        output.WriteUInt64(PrivilegeType);
      }
      if (CoreUserType != 0UL) {
        output.WriteRawTag(136, 1);
        output.WriteUInt64(CoreUserType);
      }
      if (TailText.Length != 0) {
        output.WriteRawTag(146, 1);
        output.WriteString(TailText);
      }
      if (contributionV2_ != null) {
        output.WriteRawTag(154, 1);
        output.WriteMessage(ContributionV2);
      }
      if (groupMedal_ != null) {
        output.WriteRawTag(162, 1);
        output.WriteMessage(GroupMedal);
      }
      if (IsMystery != false) {
        output.WriteRawTag(168, 1);
        output.WriteBool(IsMystery);
      }
      if (uinfo_ != null) {
        output.WriteRawTag(178, 1);
        output.WriteMessage(Uinfo);
      }
      if (relationTail_ != null) {
        output.WriteRawTag(186, 1);
        output.WriteMessage(RelationTail);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Uid != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(Uid);
      }
      if (Uname.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Uname);
      }
      if (UnameColor.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(UnameColor);
      }
      size += identities_.CalculateSize(_repeated_identities_codec);
      if (MsgType != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(MsgType);
      }
      if (Roomid != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(Roomid);
      }
      if (Timestamp != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(Timestamp);
      }
      if (Score != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(Score);
      }
      if (fansMedal_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(FansMedal);
      }
      if (IsSpread != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(IsSpread);
      }
      if (SpreadInfo.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(SpreadInfo);
      }
      if (contribution_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Contribution);
      }
      if (SpreadDesc.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(SpreadDesc);
      }
      if (TailIcon != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(TailIcon);
      }
      if (TriggerTime != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(TriggerTime);
      }
      if (PrivilegeType != 0UL) {
        size += 2 + pb::CodedOutputStream.ComputeUInt64Size(PrivilegeType);
      }
      if (CoreUserType != 0UL) {
        size += 2 + pb::CodedOutputStream.ComputeUInt64Size(CoreUserType);
      }
      if (TailText.Length != 0) {
        size += 2 + pb::CodedOutputStream.ComputeStringSize(TailText);
      }
      if (contributionV2_ != null) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(ContributionV2);
      }
      if (groupMedal_ != null) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(GroupMedal);
      }
      if (IsMystery != false) {
        size += 2 + 1;
      }
      if (uinfo_ != null) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(Uinfo);
      }
      if (relationTail_ != null) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(RelationTail);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(InteractWordV2 other) {
      if (other == null) {
        return;
      }
      if (other.Uid != 0UL) {
        Uid = other.Uid;
      }
      if (other.Uname.Length != 0) {
        Uname = other.Uname;
      }
      if (other.UnameColor.Length != 0) {
        UnameColor = other.UnameColor;
      }
      identities_.Add(other.identities_);
      if (other.MsgType != 0UL) {
        MsgType = other.MsgType;
      }
      if (other.Roomid != 0UL) {
        Roomid = other.Roomid;
      }
      if (other.Timestamp != 0UL) {
        Timestamp = other.Timestamp;
      }
      if (other.Score != 0UL) {
        Score = other.Score;
      }
      if (other.fansMedal_ != null) {
        if (fansMedal_ == null) {
          FansMedal = new global::FansMedalInfo();
        }
        FansMedal.MergeFrom(other.FansMedal);
      }
      if (other.IsSpread != 0UL) {
        IsSpread = other.IsSpread;
      }
      if (other.SpreadInfo.Length != 0) {
        SpreadInfo = other.SpreadInfo;
      }
      if (other.contribution_ != null) {
        if (contribution_ == null) {
          Contribution = new global::ContributionInfo();
        }
        Contribution.MergeFrom(other.Contribution);
      }
      if (other.SpreadDesc.Length != 0) {
        SpreadDesc = other.SpreadDesc;
      }
      if (other.TailIcon != 0UL) {
        TailIcon = other.TailIcon;
      }
      if (other.TriggerTime != 0UL) {
        TriggerTime = other.TriggerTime;
      }
      if (other.PrivilegeType != 0UL) {
        PrivilegeType = other.PrivilegeType;
      }
      if (other.CoreUserType != 0UL) {
        CoreUserType = other.CoreUserType;
      }
      if (other.TailText.Length != 0) {
        TailText = other.TailText;
      }
      if (other.contributionV2_ != null) {
        if (contributionV2_ == null) {
          ContributionV2 = new global::ContributionInfoV2();
        }
        ContributionV2.MergeFrom(other.ContributionV2);
      }
      if (other.groupMedal_ != null) {
        if (groupMedal_ == null) {
          GroupMedal = new global::GroupMedalBrief();
        }
        GroupMedal.MergeFrom(other.GroupMedal);
      }
      if (other.IsMystery != false) {
        IsMystery = other.IsMystery;
      }
      if (other.uinfo_ != null) {
        if (uinfo_ == null) {
          Uinfo = new global::UserInfo();
        }
        Uinfo.MergeFrom(other.Uinfo);
      }
      if (other.relationTail_ != null) {
        if (relationTail_ == null) {
          RelationTail = new global::UserAnchorRelation();
        }
        RelationTail.MergeFrom(other.RelationTail);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Uid = input.ReadUInt64();
            break;
          }
          case 18: {
            Uname = input.ReadString();
            break;
          }
          case 26: {
            UnameColor = input.ReadString();
            break;
          }
          case 34:
          case 32: {
            identities_.AddEntriesFrom(input, _repeated_identities_codec);
            break;
          }
          case 40: {
            MsgType = input.ReadUInt64();
            break;
          }
          case 48: {
            Roomid = input.ReadUInt64();
            break;
          }
          case 56: {
            Timestamp = input.ReadUInt64();
            break;
          }
          case 64: {
            Score = input.ReadUInt64();
            break;
          }
          case 74: {
            if (fansMedal_ == null) {
              FansMedal = new global::FansMedalInfo();
            }
            input.ReadMessage(FansMedal);
            break;
          }
          case 80: {
            IsSpread = input.ReadUInt64();
            break;
          }
          case 90: {
            SpreadInfo = input.ReadString();
            break;
          }
          case 98: {
            if (contribution_ == null) {
              Contribution = new global::ContributionInfo();
            }
            input.ReadMessage(Contribution);
            break;
          }
          case 106: {
            SpreadDesc = input.ReadString();
            break;
          }
          case 112: {
            TailIcon = input.ReadUInt64();
            break;
          }
          case 120: {
            TriggerTime = input.ReadUInt64();
            break;
          }
          case 128: {
            PrivilegeType = input.ReadUInt64();
            break;
          }
          case 136: {
            CoreUserType = input.ReadUInt64();
            break;
          }
          case 146: {
            TailText = input.ReadString();
            break;
          }
          case 154: {
            if (contributionV2_ == null) {
              ContributionV2 = new global::ContributionInfoV2();
            }
            input.ReadMessage(ContributionV2);
            break;
          }
          case 162: {
            if (groupMedal_ == null) {
              GroupMedal = new global::GroupMedalBrief();
            }
            input.ReadMessage(GroupMedal);
            break;
          }
          case 168: {
            IsMystery = input.ReadBool();
            break;
          }
          case 178: {
            if (uinfo_ == null) {
              Uinfo = new global::UserInfo();
            }
            input.ReadMessage(Uinfo);
            break;
          }
          case 186: {
            if (relationTail_ == null) {
              RelationTail = new global::UserAnchorRelation();
            }
            input.ReadMessage(RelationTail);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Uid = input.ReadUInt64();
            break;
          }
          case 18: {
            Uname = input.ReadString();
            break;
          }
          case 26: {
            UnameColor = input.ReadString();
            break;
          }
          case 34:
          case 32: {
            identities_.AddEntriesFrom(ref input, _repeated_identities_codec);
            break;
          }
          case 40: {
            MsgType = input.ReadUInt64();
            break;
          }
          case 48: {
            Roomid = input.ReadUInt64();
            break;
          }
          case 56: {
            Timestamp = input.ReadUInt64();
            break;
          }
          case 64: {
            Score = input.ReadUInt64();
            break;
          }
          case 74: {
            if (fansMedal_ == null) {
              FansMedal = new global::FansMedalInfo();
            }
            input.ReadMessage(FansMedal);
            break;
          }
          case 80: {
            IsSpread = input.ReadUInt64();
            break;
          }
          case 90: {
            SpreadInfo = input.ReadString();
            break;
          }
          case 98: {
            if (contribution_ == null) {
              Contribution = new global::ContributionInfo();
            }
            input.ReadMessage(Contribution);
            break;
          }
          case 106: {
            SpreadDesc = input.ReadString();
            break;
          }
          case 112: {
            TailIcon = input.ReadUInt64();
            break;
          }
          case 120: {
            TriggerTime = input.ReadUInt64();
            break;
          }
          case 128: {
            PrivilegeType = input.ReadUInt64();
            break;
          }
          case 136: {
            CoreUserType = input.ReadUInt64();
            break;
          }
          case 146: {
            TailText = input.ReadString();
            break;
          }
          case 154: {
            if (contributionV2_ == null) {
              ContributionV2 = new global::ContributionInfoV2();
            }
            input.ReadMessage(ContributionV2);
            break;
          }
          case 162: {
            if (groupMedal_ == null) {
              GroupMedal = new global::GroupMedalBrief();
            }
            input.ReadMessage(GroupMedal);
            break;
          }
          case 168: {
            IsMystery = input.ReadBool();
            break;
          }
          case 178: {
            if (uinfo_ == null) {
              Uinfo = new global::UserInfo();
            }
            input.ReadMessage(Uinfo);
            break;
          }
          case 186: {
            if (relationTail_ == null) {
              RelationTail = new global::UserAnchorRelation();
            }
            input.ReadMessage(RelationTail);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
