// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: OnlineRankV3.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace BLiveAPI.Protos {

  /// <summary>Holder for reflection information generated from OnlineRankV3.proto</summary>
  public static partial class OnlineRankV3Reflection {

    #region Descriptor
    /// <summary>File descriptor for OnlineRankV3.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static OnlineRankV3Reflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChJPbmxpbmVSYW5rVjMucHJvdG8SF2JpbGliaWxpLmxpdmUucmFua2RiLnYx",
            "Gg5Vc2VyRGFndy5wcm90byKgAwoRR29sZFJhbmtCcm9hZGNhc3QSEQoJcmFu",
            "a190eXBlGAEgASgJEk4KBGxpc3QYAiADKAsyQC5iaWxpYmlsaS5saXZlLnJh",
            "bmtkYi52MS5Hb2xkUmFua0Jyb2FkY2FzdC5Hb2xkUmFua0Jyb2FkY2FzdEl0",
            "ZW0SVQoLb25saW5lX2xpc3QYAyADKAsyQC5iaWxpYmlsaS5saXZlLnJhbmtk",
            "Yi52MS5Hb2xkUmFua0Jyb2FkY2FzdC5Hb2xkUmFua0Jyb2FkY2FzdEl0ZW0a",
            "0AEKFUdvbGRSYW5rQnJvYWRjYXN0SXRlbRILCgN1aWQYASABKAMSDAoEZmFj",
            "ZRgCIAEoCRINCgVzY29yZRgDIAEoCRINCgV1bmFtZRgEIAEoCRIMCgRyYW5r",
            "GAUgASgDEhMKC2d1YXJkX2xldmVsGAYgASgDEhIKCmlzX215c3RlcnkYByAB",
            "KAgSRwoFdWluZm8YCCABKAsyOC5iaWxpYmlsaS5saXZlLmNvbXBvbmVudC5j",
            "b21tb25fbW9kZWwudXNlcl9kYWd3LlVzZXJJbmZvQhKqAg9CTGl2ZUFQSS5Q",
            "cm90b3NiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Bilibili.Live.Component.CommonModel.UserDagw.UserDagwReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::BLiveAPI.Protos.GoldRankBroadcast), global::BLiveAPI.Protos.GoldRankBroadcast.Parser, new[]{ "RankType", "List", "OnlineList" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { new pbr::GeneratedClrTypeInfo(typeof(global::BLiveAPI.Protos.GoldRankBroadcast.Types.GoldRankBroadcastItem), global::BLiveAPI.Protos.GoldRankBroadcast.Types.GoldRankBroadcastItem.Parser, new[]{ "Uid", "Face", "Score", "Uname", "Rank", "GuardLevel", "IsMystery", "Uinfo" }, null, null, null, null)})
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  /// `ONLINE_RANK_V3` cmd
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class GoldRankBroadcast : pb::IMessage<GoldRankBroadcast>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<GoldRankBroadcast> _parser = new pb::MessageParser<GoldRankBroadcast>(() => new GoldRankBroadcast());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<GoldRankBroadcast> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::BLiveAPI.Protos.OnlineRankV3Reflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GoldRankBroadcast() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GoldRankBroadcast(GoldRankBroadcast other) : this() {
      rankType_ = other.rankType_;
      list_ = other.list_.Clone();
      onlineList_ = other.onlineList_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GoldRankBroadcast Clone() {
      return new GoldRankBroadcast(this);
    }

    /// <summary>Field number for the "rank_type" field.</summary>
    public const int RankTypeFieldNumber = 1;
    private string rankType_ = "";
    /// <summary>
    /// 排行类型
    /// `gold-rank`: 高能用户(似乎不下发，记录缺失)
    /// `online_rank`: 在线用户
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string RankType {
      get { return rankType_; }
      set {
        rankType_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "list" field.</summary>
    public const int ListFieldNumber = 2;
    private static readonly pb::FieldCodec<global::BLiveAPI.Protos.GoldRankBroadcast.Types.GoldRankBroadcastItem> _repeated_list_codec
        = pb::FieldCodec.ForMessage(18, global::BLiveAPI.Protos.GoldRankBroadcast.Types.GoldRankBroadcastItem.Parser);
    private readonly pbc::RepeatedField<global::BLiveAPI.Protos.GoldRankBroadcast.Types.GoldRankBroadcastItem> list_ = new pbc::RepeatedField<global::BLiveAPI.Protos.GoldRankBroadcast.Types.GoldRankBroadcastItem>();
    /// <summary>
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::BLiveAPI.Protos.GoldRankBroadcast.Types.GoldRankBroadcastItem> List {
      get { return list_; }
    }

    /// <summary>Field number for the "online_list" field.</summary>
    public const int OnlineListFieldNumber = 3;
    private static readonly pb::FieldCodec<global::BLiveAPI.Protos.GoldRankBroadcast.Types.GoldRankBroadcastItem> _repeated_onlineList_codec
        = pb::FieldCodec.ForMessage(26, global::BLiveAPI.Protos.GoldRankBroadcast.Types.GoldRankBroadcastItem.Parser);
    private readonly pbc::RepeatedField<global::BLiveAPI.Protos.GoldRankBroadcast.Types.GoldRankBroadcastItem> onlineList_ = new pbc::RepeatedField<global::BLiveAPI.Protos.GoldRankBroadcast.Types.GoldRankBroadcastItem>();
    /// <summary>
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::BLiveAPI.Protos.GoldRankBroadcast.Types.GoldRankBroadcastItem> OnlineList {
      get { return onlineList_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as GoldRankBroadcast);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(GoldRankBroadcast other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (RankType != other.RankType) return false;
      if(!list_.Equals(other.list_)) return false;
      if(!onlineList_.Equals(other.onlineList_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (RankType.Length != 0) hash ^= RankType.GetHashCode();
      hash ^= list_.GetHashCode();
      hash ^= onlineList_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (RankType.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(RankType);
      }
      list_.WriteTo(output, _repeated_list_codec);
      onlineList_.WriteTo(output, _repeated_onlineList_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (RankType.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(RankType);
      }
      list_.WriteTo(ref output, _repeated_list_codec);
      onlineList_.WriteTo(ref output, _repeated_onlineList_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (RankType.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(RankType);
      }
      size += list_.CalculateSize(_repeated_list_codec);
      size += onlineList_.CalculateSize(_repeated_onlineList_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(GoldRankBroadcast other) {
      if (other == null) {
        return;
      }
      if (other.RankType.Length != 0) {
        RankType = other.RankType;
      }
      list_.Add(other.list_);
      onlineList_.Add(other.onlineList_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            RankType = input.ReadString();
            break;
          }
          case 18: {
            list_.AddEntriesFrom(input, _repeated_list_codec);
            break;
          }
          case 26: {
            onlineList_.AddEntriesFrom(input, _repeated_onlineList_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            RankType = input.ReadString();
            break;
          }
          case 18: {
            list_.AddEntriesFrom(ref input, _repeated_list_codec);
            break;
          }
          case 26: {
            onlineList_.AddEntriesFrom(ref input, _repeated_onlineList_codec);
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the GoldRankBroadcast message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      /// <summary>
      /// 单个排行数据
      /// </summary>
      [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
      public sealed partial class GoldRankBroadcastItem : pb::IMessage<GoldRankBroadcastItem>
      #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          , pb::IBufferMessage
      #endif
      {
        private static readonly pb::MessageParser<GoldRankBroadcastItem> _parser = new pb::MessageParser<GoldRankBroadcastItem>(() => new GoldRankBroadcastItem());
        private pb::UnknownFieldSet _unknownFields;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pb::MessageParser<GoldRankBroadcastItem> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pbr::MessageDescriptor Descriptor {
          get { return global::BLiveAPI.Protos.GoldRankBroadcast.Descriptor.NestedTypes[0]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        pbr::MessageDescriptor pb::IMessage.Descriptor {
          get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public GoldRankBroadcastItem() {
          OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public GoldRankBroadcastItem(GoldRankBroadcastItem other) : this() {
          uid_ = other.uid_;
          face_ = other.face_;
          score_ = other.score_;
          uname_ = other.uname_;
          rank_ = other.rank_;
          guardLevel_ = other.guardLevel_;
          isMystery_ = other.isMystery_;
          uinfo_ = other.uinfo_ != null ? other.uinfo_.Clone() : null;
          _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public GoldRankBroadcastItem Clone() {
          return new GoldRankBroadcastItem(this);
        }

        /// <summary>Field number for the "uid" field.</summary>
        public const int UidFieldNumber = 1;
        private long uid_;
        /// <summary>
        /// 用户mid
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public long Uid {
          get { return uid_; }
          set {
            uid_ = value;
          }
        }

        /// <summary>Field number for the "face" field.</summary>
        public const int FaceFieldNumber = 2;
        private string face_ = "";
        /// <summary>
        /// 头像
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public string Face {
          get { return face_; }
          set {
            face_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
          }
        }

        /// <summary>Field number for the "score" field.</summary>
        public const int ScoreFieldNumber = 3;
        private string score_ = "";
        /// <summary>
        /// 贡献值
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public string Score {
          get { return score_; }
          set {
            score_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
          }
        }

        /// <summary>Field number for the "uname" field.</summary>
        public const int UnameFieldNumber = 4;
        private string uname_ = "";
        /// <summary>
        /// 用户名称
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public string Uname {
          get { return uname_; }
          set {
            uname_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
          }
        }

        /// <summary>Field number for the "rank" field.</summary>
        public const int RankFieldNumber = 5;
        private long rank_;
        /// <summary>
        /// 在榜单中的排名
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public long Rank {
          get { return rank_; }
          set {
            rank_ = value;
          }
        }

        /// <summary>Field number for the "guard_level" field.</summary>
        public const int GuardLevelFieldNumber = 6;
        private long guardLevel_;
        /// <summary>
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public long GuardLevel {
          get { return guardLevel_; }
          set {
            guardLevel_ = value;
          }
        }

        /// <summary>Field number for the "is_mystery" field.</summary>
        public const int IsMysteryFieldNumber = 7;
        private bool isMystery_;
        /// <summary>
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool IsMystery {
          get { return isMystery_; }
          set {
            isMystery_ = value;
          }
        }

        /// <summary>Field number for the "uinfo" field.</summary>
        public const int UinfoFieldNumber = 8;
        private global::Bilibili.Live.Component.CommonModel.UserDagw.UserInfo uinfo_;
        /// <summary>
        /// 用户信息
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public global::Bilibili.Live.Component.CommonModel.UserDagw.UserInfo Uinfo {
          get { return uinfo_; }
          set {
            uinfo_ = value;
          }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override bool Equals(object other) {
          return Equals(other as GoldRankBroadcastItem);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool Equals(GoldRankBroadcastItem other) {
          if (ReferenceEquals(other, null)) {
            return false;
          }
          if (ReferenceEquals(other, this)) {
            return true;
          }
          if (Uid != other.Uid) return false;
          if (Face != other.Face) return false;
          if (Score != other.Score) return false;
          if (Uname != other.Uname) return false;
          if (Rank != other.Rank) return false;
          if (GuardLevel != other.GuardLevel) return false;
          if (IsMystery != other.IsMystery) return false;
          if (!object.Equals(Uinfo, other.Uinfo)) return false;
          return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override int GetHashCode() {
          int hash = 1;
          if (Uid != 0L) hash ^= Uid.GetHashCode();
          if (Face.Length != 0) hash ^= Face.GetHashCode();
          if (Score.Length != 0) hash ^= Score.GetHashCode();
          if (Uname.Length != 0) hash ^= Uname.GetHashCode();
          if (Rank != 0L) hash ^= Rank.GetHashCode();
          if (GuardLevel != 0L) hash ^= GuardLevel.GetHashCode();
          if (IsMystery != false) hash ^= IsMystery.GetHashCode();
          if (uinfo_ != null) hash ^= Uinfo.GetHashCode();
          if (_unknownFields != null) {
            hash ^= _unknownFields.GetHashCode();
          }
          return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override string ToString() {
          return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void WriteTo(pb::CodedOutputStream output) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          output.WriteRawMessage(this);
        #else
          if (Uid != 0L) {
            output.WriteRawTag(8);
            output.WriteInt64(Uid);
          }
          if (Face.Length != 0) {
            output.WriteRawTag(18);
            output.WriteString(Face);
          }
          if (Score.Length != 0) {
            output.WriteRawTag(26);
            output.WriteString(Score);
          }
          if (Uname.Length != 0) {
            output.WriteRawTag(34);
            output.WriteString(Uname);
          }
          if (Rank != 0L) {
            output.WriteRawTag(40);
            output.WriteInt64(Rank);
          }
          if (GuardLevel != 0L) {
            output.WriteRawTag(48);
            output.WriteInt64(GuardLevel);
          }
          if (IsMystery != false) {
            output.WriteRawTag(56);
            output.WriteBool(IsMystery);
          }
          if (uinfo_ != null) {
            output.WriteRawTag(66);
            output.WriteMessage(Uinfo);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(output);
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
          if (Uid != 0L) {
            output.WriteRawTag(8);
            output.WriteInt64(Uid);
          }
          if (Face.Length != 0) {
            output.WriteRawTag(18);
            output.WriteString(Face);
          }
          if (Score.Length != 0) {
            output.WriteRawTag(26);
            output.WriteString(Score);
          }
          if (Uname.Length != 0) {
            output.WriteRawTag(34);
            output.WriteString(Uname);
          }
          if (Rank != 0L) {
            output.WriteRawTag(40);
            output.WriteInt64(Rank);
          }
          if (GuardLevel != 0L) {
            output.WriteRawTag(48);
            output.WriteInt64(GuardLevel);
          }
          if (IsMystery != false) {
            output.WriteRawTag(56);
            output.WriteBool(IsMystery);
          }
          if (uinfo_ != null) {
            output.WriteRawTag(66);
            output.WriteMessage(Uinfo);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(ref output);
          }
        }
        #endif

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int CalculateSize() {
          int size = 0;
          if (Uid != 0L) {
            size += 1 + pb::CodedOutputStream.ComputeInt64Size(Uid);
          }
          if (Face.Length != 0) {
            size += 1 + pb::CodedOutputStream.ComputeStringSize(Face);
          }
          if (Score.Length != 0) {
            size += 1 + pb::CodedOutputStream.ComputeStringSize(Score);
          }
          if (Uname.Length != 0) {
            size += 1 + pb::CodedOutputStream.ComputeStringSize(Uname);
          }
          if (Rank != 0L) {
            size += 1 + pb::CodedOutputStream.ComputeInt64Size(Rank);
          }
          if (GuardLevel != 0L) {
            size += 1 + pb::CodedOutputStream.ComputeInt64Size(GuardLevel);
          }
          if (IsMystery != false) {
            size += 1 + 1;
          }
          if (uinfo_ != null) {
            size += 1 + pb::CodedOutputStream.ComputeMessageSize(Uinfo);
          }
          if (_unknownFields != null) {
            size += _unknownFields.CalculateSize();
          }
          return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(GoldRankBroadcastItem other) {
          if (other == null) {
            return;
          }
          if (other.Uid != 0L) {
            Uid = other.Uid;
          }
          if (other.Face.Length != 0) {
            Face = other.Face;
          }
          if (other.Score.Length != 0) {
            Score = other.Score;
          }
          if (other.Uname.Length != 0) {
            Uname = other.Uname;
          }
          if (other.Rank != 0L) {
            Rank = other.Rank;
          }
          if (other.GuardLevel != 0L) {
            GuardLevel = other.GuardLevel;
          }
          if (other.IsMystery != false) {
            IsMystery = other.IsMystery;
          }
          if (other.uinfo_ != null) {
            if (uinfo_ == null) {
              Uinfo = new global::Bilibili.Live.Component.CommonModel.UserDagw.UserInfo();
            }
            Uinfo.MergeFrom(other.Uinfo);
          }
          _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(pb::CodedInputStream input) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          input.ReadRawMessage(this);
        #else
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
          if ((tag & 7) == 4) {
            // Abort on any end group tag.
            return;
          }
          switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                break;
              case 8: {
                Uid = input.ReadInt64();
                break;
              }
              case 18: {
                Face = input.ReadString();
                break;
              }
              case 26: {
                Score = input.ReadString();
                break;
              }
              case 34: {
                Uname = input.ReadString();
                break;
              }
              case 40: {
                Rank = input.ReadInt64();
                break;
              }
              case 48: {
                GuardLevel = input.ReadInt64();
                break;
              }
              case 56: {
                IsMystery = input.ReadBool();
                break;
              }
              case 66: {
                if (uinfo_ == null) {
                  Uinfo = new global::Bilibili.Live.Component.CommonModel.UserDagw.UserInfo();
                }
                input.ReadMessage(Uinfo);
                break;
              }
            }
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
          if ((tag & 7) == 4) {
            // Abort on any end group tag.
            return;
          }
          switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                break;
              case 8: {
                Uid = input.ReadInt64();
                break;
              }
              case 18: {
                Face = input.ReadString();
                break;
              }
              case 26: {
                Score = input.ReadString();
                break;
              }
              case 34: {
                Uname = input.ReadString();
                break;
              }
              case 40: {
                Rank = input.ReadInt64();
                break;
              }
              case 48: {
                GuardLevel = input.ReadInt64();
                break;
              }
              case 56: {
                IsMystery = input.ReadBool();
                break;
              }
              case 66: {
                if (uinfo_ == null) {
                  Uinfo = new global::Bilibili.Live.Component.CommonModel.UserDagw.UserInfo();
                }
                input.ReadMessage(Uinfo);
                break;
              }
            }
          }
        }
        #endif

      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
